import = [
    "./catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
opacity = 0.9

padding.x = 10
padding.y = 10

decorations = "None"

[font]
size = 14.0
# also used for bold, italic, bold_italic
normal.family = "FiraCode Nerd Font Mono"

