[colors.bright]
black = "#6e6a86"
blue = "#c4a7e7"
cyan = "#9ccfd8"
green = "#31748f"
magenta = "#f6c177"
red = "#eb6f92"
white = "#524f67"
yellow = "#ebbcba"

[colors.cursor]
cursor = "#e0def4"
text = "#191724"

[colors.normal]
black = "#191724"
blue = "#c4a7e7"
cyan = "#9ccfd8"
green = "#31748f"
magenta = "#f6c177"
red = "#eb6f92"
white = "#e0def4"
yellow = "#ebbcba"

[colors.primary]
background = "#191724"
bright_foreground = "#524f67"
foreground = "#e0def4"

[colors.selection]
background = "#26233a"
text = "#e0def4"

[env]
TERM = "xterm-256color"

[font]
size = 14
[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"

